FROM patroni-rhel8-base:latest

# Metadata
LABEL maintainer="Jean-Marie RENOUARD<jmrenouard@gmail.com>"
LABEL org.opencontainers.image.title="Patroni Lab RHEL 8 ETCD"
LABEL description="ETCD 3.6 image based on RHEL 8 UBI"

# Install ETCD
RUN dnf install -y etcd && \
    dnf clean all

# Expose ETCD ports
EXPOSE 2379 2380 22

# Entrypoint script handles cluster logic
ENTRYPOINT ["/bin/bash", "/scripts/manage/entrypoint_etcd.sh"]
